name:                benchmark
version:             0.1.0.0
github:              "githubuser/benchmark"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/benchmark#readme>

dependencies:
- base >= 4.7 && < 5
- text >= 1.2
- aeson >= 1.5.6
- bytestring >= 0.10.12
- time >= 1.9.3
- containers >= 0.4.0
- transformers >= 0.5.6.2
- mtl >= 2.2.2

library:
  source-dirs: src

executables:
  benchmark-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - benchmark

tests:
  benchmark-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - benchmark
    - tasty
    - tasty-hunit
